export const skills = [
  { id: 1, name: 'React 18' },
  { id: 2, name: 'JavaScript' },
  { id: 3, name: 'Custom Hook' },
  { id: 4, name: 'Tailwindcss' },
  { id: 5, name: 'VCS - Git Hub' },
  { id: 6, name: 'Eslint' },
  { id: 7, name: 'Prettier' },
  { id: 8, name: 'JSDoc' },
  { id: 9, name: 'Vite' },
  { id: 10, name: 'HTTP Protocol' },
  { id: 11, name: 'CRUD' },
  { id: 12, name: 'Promises' },
  { id: 13, name: 'Async/Await' },
  { id: 14, name: 'Exception handling' },
  { id: 15, name: 'Design Patterns' },
  { id: 16, name: 'OOP' },
  { id: 17, name: 'Data Structures' },
  { id: 18, name: 'SQL basics' },
  { id: 19, name: 'MySQL' },
  { id: 20, name: 'Scrum basics' },
];
